main: fr.enderstevegamer.naturaldisastersplugin.Main
name: NaturalDisastersPlugin
version: 1.0
api-version: 1.17
commands:
   triggerEvent:
      description: Trigger a natural disaster
      permission: naturaldisastersplugin.triggerEvent
      permission-message: You don't have the permission to trigger a natural disaster
      aliases: [te]
      tab-completer: fr.enderstevegamer.naturaldisastersplugin.TabCompleter